services:
  db:
    image: mysql:8.0
    container_name: tech-tavern-mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: tech-tavern-api
    env_file: .env
    ports:
      - "3009:3009"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data:
